### ISSUE TITLE
unRaid versioning

### ISSUE THREAD

**Issue by Squidly271** [limetech/webgui#193]
FYI, unRaid now has a version of 6.4.0_rc10b while the previous standard you've been using should have been 6.4.0-rc10b

Luckily, PHP version_compare still understands that _rc10b is a later version than -rc9f, but any bash scripts etc might fail when checking for versions.

Be consistent

**Comment by limetech** [comment]
Yeah we had to do that because the plugin system uses strcmp() instead of version_compare().  If we had kept with the '-' then -rc10b would sort lower than -rc9f (last release).

We've known about this issue and knew that we needed to change strcmp() in certain places to version_compare() and the time to do this is on a minor release transition, eg, from 6.3 to 6.4, and in fact when 6.4.0-rc1 came out I looked over the code and thought the change had been put in.  I just didn't do a good enough job "looking over the code".  We'll put this fix in when we move to 6.5.

**Comment by bergware** [comment]
The reason it wasn't included is because _version_compare_ doesn't work properly when comparing versions like 2017.11.04a and 2017.11.04b.

When the code is revised we need to make a distinction between unRAID version numbering and plugins version numbering.

**Comment by bergware** [comment]
Made a PR which uses **version_compare** to check unRAID versions and **strcmp** to check plugin versions.
